### ISSUE TITLE
Support for MPI

### ISSUE THREAD

**Issue by vishal-deka** [memtt/numaprof#36]
Does the tool work for MPI programs? If yes, can it be used as `mpirun [options] numprof <prog>`

**Comment by svalat** [comment]
Hi,
I made a dedicated support for MALT but not for NUMAPROF. But by default the tool will create a profile file for each process you have launched. The point which is not so nice is that they will be identified by their PID.

If you really need it tell me I have an option in my head to make it in a simple way by extractoin the rank from the environment variable.

In MALT I use a MPI wrapper which call MPI_Comm_ranl() but I cannot do the same trick in NUMAPROF due to usage of PIN.

**Comment by vishal-deka** [comment]
I tested with some MPI programs and it seems to work fine. Although the generated profiles are identified by PID, it will be fine for my work.

**Comment by svalat** [comment]
Get an idea to make it by handling the specific MPI env variable for the various MPI flavors (intelMPI, openmpi, mpich).
It is not perfect and fully generic but it can already be a nice and simple first way.

**Comment by svalat** [comment]
Done in `master` will be in next minor release.
