### ISSUE TITLE
Segmentation Fault with OpenMP codes

### ISSUE THREAD

**Issue by rohanverma94** [memtt/numaprof#38]
I've an openmp code, 
```cpp
#include <stdio.h>
#include <omp.h>

void socket_init(int socket_num)
{
   int n_procs;

   n_procs = omp_get_place_num_procs(socket_num);
   #pragma omp parallel num_threads(n_procs) proc_bind(close)
   {
      printf("Reporting in from socket num, thread num:  %d %d\n", 
                                socket_num,omp_get_thread_num() );
   }
}

int main()
{
   int n_sockets, socket_num;

   omp_set_nested(1);              // or export OMP_NESTED=true
   omp_set_max_active_levels(2);   // or export OMP_MAX_ACTIVE_LEVELS=2

   n_sockets = omp_get_num_places();
   #pragma omp parallel num_threads(n_sockets) private(socket_num) \
                        proc_bind(spread)
   {
      socket_num = omp_get_place_num();
      socket_init(socket_num);
   }

   return 0;
}
```
When I compiled it and applied numaprof over it, I get following -

/usr/local/bin/numaprof: line 78: 66018 Segmentation fault      (core dumped) ${PINTOOL_PIN} -t ${NUMAPROF_PREFIX}/lib/libnumaprof-pintool.so -- "$@"

**Comment by svalat** [comment]
Thanks very much for reporting the issue.

Fixed in master branch by supporting pintool 3.24, more details here :

I reproduced your issue by running on the last ubuntu version (22;04) with the last supported pintool version by numaprof (3.16). This version of pintool fails to instrument the libc which we can see by using the -V option on the numaprof command :

```
$ numaprof -V /tmp/main
NUMAPROF: Get cpu number : 8
NUMAPROF: Size = 1024, ncpu = 8
NUMAPROF: Thread is binded on NUMA 0
NUMAPROF: Numa initial mapping : 0
NUMAPROF: Numa initial mem mapping : NO_BIND
NUMAPROF: register thread 49408
NUMAPROF: instr malloc from /lib/x86_64-linux-gnu/libc.so.6
/home/sebv/testinstall/bin/numaprof : ligne 78 : 49408 Erreur de segmentation  ${PINTOOL_PIN} -t ${NUMAPROF_PREFIX}/lib/libnumaprof-pintool.so -- "$@"
```

The issue is fixed by patching numaprof to build with the last version of pintool (3.24) which successfully run on ubuntu 22.04 with your test program.

The fix is currently in master branch, I will make an official release as soon as possible to make it available easily for everybody, please use the git repo while waiting the official release.

Please confirm it fixes the issue on your side if possible.

**Comment by svalat** [comment]
Oops sorry I closed before waiting your answer by adding (closes) in my patch submission, please confirm it fixes on your side.

**Comment by rohanverma94** [comment]
Thanks! the patch is working with pin-tool-3.24. I'll mark the issue "closed".
